apiVersion: v1
kind: Pod
metadata:
  name: result-pod
  labels:
    name: result-pod
    app: voting-app
spec:
  containers:
  - name: result-container
    image: docker/example-voting-app-result
    ports:
    - containerPort: 80